#!/usr/bin/env zsh
zstyle ':completion:*' completer _complete _ignored _correct _approximate
zstyle ':completion:*' completions 1
zstyle ':completion:*' file-sort name
zstyle ':completion:*' glob 1
zstyle ':completion:*' ignore-parents parent pwd
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'l:|=* r:|=*' 'r:|=**'
zstyle ':completion:*' max-errors 2
zstyle ':completion:*' menu select
zstyle ':completion:*' substitute 1
zstyle :compinstall filename "$ZDOTDIR/.zshrc"
autoload -Uz compinit && compinit -d "$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"

bindkey '^[[1;5D' backward-word      # Ctrl + LeftArrow
bindkey '^[[1;5C' forward-word       # Ctrl + RightArrow
bindkey '^[[3~'   delete-char        # Delete
bindkey ^H        backward-kill-word # Ctrl + Backspace
bindkey '^[[3;5~' kill-word          # Ctrl + Delete

setopt hist_ignore_all_dups
setopt hist_ignore_space
