#!/usr/bin/env sh
alias d='doas '
alias v=nvim
alias g=git
alias c=cargo
alias t=trash
alias ls='ls -hpF --group-directories-first --color=auto'
alias xi=xbps-install
alias xr=xbps-remove
alias xq=xbps-query
alias xp=xbps-pkgdb
