local map = vim.keymap.set
map({ 'n', 'v', 'x' }, ';', ':')
map('n', '<leader>w', ':update<cr>')
map('n', '<c-x>', ':quit!<cr>')
map('n', '<c-s-x>', ':quitall!<cr>')
for i = 1, 9 do
    map('n', '<c-' .. i .. '>', ':buffer ' .. i .. '<cr>')
end
map('n', '<c-tab>', ':buffer #<cr>')
map('n', '<c-cr>', ':vsplit | wincmd l<cr>')
map('n', '<c-s-cr>', ':split | wincmd j<cr>')
map('c', '<c-h>', '<left>')
map('c', '<c-j>', '<down>')
map('c', '<c-k>', '<up>')
map('c', '<c-l>', '<right>')
map('n', '<c-h>', '<c-w>h')
map('n', '<c-j>', '<c-w>j')
map('n', '<c-k>', '<c-w>k')
map('n', '<c-l>', '<c-w>l')
map('n', '<c-s-h>', ':vertical resize -5<cr>')
map('n', '<c-s-j>', ':resize +2<cr>')
map('n', '<c-s-k>', ':resize -2<cr>')
map('n', '<c-s-l>', ':vertical resize +5<cr>')
map({ 'n', 'x' }, '<c-n>', [[<esc>:'<,'>normal ]])
map({ 'n', 'x' }, '<c-s>', [[<esc>:'<,'>s/\V]])
map('n', '<leader> ', function() Snacks.picker.resume() end)
map('n', '<leader>/', function() Snacks.picker.grep() end)
map('n', '<leader>f', function() Snacks.picker.files() end)
map('n', '<leader>v', function() Snacks.picker.files({ cwd = vim.fn.stdpath('config') }) end)
map('n', '<leader>b', function() Snacks.picker.buffers() end)
map('n', '<leader>e', function() Snacks.picker.explorer() end)
map('n', '<leader>h', function() Snacks.picker.help() end)
map('n', 'gd', function() Snacks.picker.lsp_definitions() end)
map('n', 'gD', function() Snacks.picker.lsp_declarations() end)
map('n', 'gy', function() Snacks.picker.lsp_type_definitions() end)
map('n', 'gr', function() Snacks.picker.lsp_references() end)
map('n', 'gi', function() Snacks.picker.lsp_implementations() end)
map('n', 'gs', function() Snacks.picker.lsp_symbols() end)
map('n', 'gS', function() Snacks.picker.lsp_workspace_symbols() end)
map('n', '<leader>do', vim.diagnostic.open_float)
map('n', '<leader>dt', ':Trouble diagnostics toggle filter.buf=0')
map('n', '<leader>dT', ':Trouble diagnostics toggle')
